version: '3.7'
services:
  user:
    image: openjdk:11-jdk
    ports:
      - 8081:8080
    volumes:
      - ./user/data/binaries:/usr/src/user/data
      - ./user/data/config:/usr/src/user/config
    working_dir: /usr/src/user
    command: "java -jar ./data/user-demo.jar"